name: Run RSpec tests on Production Merge

on:
  push:
    branches:
      - '**'

env:
  WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}

jobs:
  test:
    name: Run RSpec tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Run RSpec tests
        run: |
          bundle exec rspec
